[alias] 
pseudo = ["run", "--bin", "pseudo", "--"]
tester = ["run", "--release", "-q", "--bin", "tester",  "--", "./examples"]
cleaner = ["run", "--release", "-q", "--bin", "cleaner"]

[env]
LIBPSEUDO="/home/alchemist/Desktop/ada/libpseudo"

